### ISSUE TITLE
invalid number of arguments to solidity function

### ISSUE THREAD

**Issue by bbrock25** [chainskills/chainlist#1]
Running this example project using MetaMask and testrpc, I am getting the following error in the javascript console when attempting to sell and article: 
```console
web3.min.js:1 Uncaught (in promise) Error: Invalid number of arguments to Solidity function
    at Object.InvalidNumberOfSolidityArgs (web3.min.js:1)
    at c.validateArgs (web3.min.js:2)
    at c.toPayload (web3.min.js:2)
    at c.call (web3.min.js:2)
    at c.execute (web3.min.js:2)
    at truffle-contract.js:136
    at Promise (<anonymous>)
    at truffle-contract.js:127
    at <anonymous>
```

could it be a web3 version issue?

(I've started the test rpc server using the provided script and imported those private keys into metamask)

**Comment by sarbogast** [comment]
I think we noticed that issue and solved it later in the course, in the lesson about deploying to the Rinkeby test network, by adding a `.toNumber()` call in line 77 of `app.js`. Unfortunately, this issue seems to pop up randomly and inconsistently, and for us it didn't pop up until we deployed the contracts to a test network. You can try and fix [this line](https://github.com/sarbogast/chainlist/blob/master/src/js/app.js#L77) and let me know if it works.
